#!/usr/bin/env bash
set -e

wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
bash Miniforge3-Linux-x86_64.sh -b

mamba install -y \
        numpy==1.24.2 \
        pandas==1.5.3 \
        pip==23.0 \
        python==3.10.9 \
        pyyaml==6.0.2 \
        scikit-learn==1.2.1 \
        scipy==1.10.0 \
        seaborn==0.12.2 \
        tqdm==4.64.1 \
        wandb==0.16.2 \
        xgboost==2.1.1 \
    && mamba clean -ya

mamba install -c conda-forge rdkit==2022.09.4 mkl==2024.0

mamba install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch

pip install https://data.pyg.org/whl/torch-1.12.0%2Bcu113/torch_cluster-1.6.0%2Bpt112cu113-cp310-cp310-linux_x86_64.whl
pip install https://data.pyg.org/whl/torch-1.12.0%2Bcu113/torch_scatter-2.1.0%2Bpt112cu113-cp310-cp310-linux_x86_64.whl
pip install https://data.pyg.org/whl/torch-1.12.0%2Bcu113/torch_sparse-0.6.16%2Bpt112cu113-cp310-cp310-linux_x86_64.whl
pip install https://data.pyg.org/whl/torch-1.12.0%2Bcu113/torch_spline_conv-1.2.1%2Bpt112cu113-cp310-cp310-linux_x86_64.whl
pip install torch-geometric==2.2.0